services:
  - type: web
    name: flask-ticket-app
    runtime: python
    buildCommand: pip install -r render-requirements.txt
    startCommand: gunicorn main:app
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: postgres
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: RENDER
        value: true
databases:
  - name: postgres
    plan: free
