"""Add serial_number column to GalleryItem

Revision ID: 1ba35720dfdf
Revises: 4f468a064ab9
Create Date: 2025-04-15 15:51:10.062194

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ba35720dfdf'
down_revision = '4f468a064ab9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gallery_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('serial_number', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gallery_item', schema=None) as batch_op:
        batch_op.drop_column('serial_number')

    # ### end Alembic commands ###
