"""Add GalleryItem column

Revision ID: 4f468a064ab9
Revises: 9bb1607e7a14
Create Date: 2025-04-15 11:38:58.636434

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f468a064ab9'
down_revision = '9bb1607e7a14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gallery_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_available', sa.Boolean(), nullable=False, server_default=sa.true()))
        batch_op.alter_column('media_url',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=255),
               nullable=False)
        batch_op.alter_column('media_type',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               nullable=False)
        batch_op.alter_column('caption',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=255),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gallery_item', schema=None) as batch_op:
        batch_op.alter_column('caption',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
        batch_op.alter_column('media_type',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('media_url',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=500),
               nullable=True)
        batch_op.drop_column('is_available')

    # ### end Alembic commands ###
