"""Update model to make media_url and media_type nullable

Revision ID: 7d1bbd9e98af
Revises: 700b1c99f0b8
Create Date: 2025-04-11 10:13:39.279078

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d1bbd9e98af'
down_revision = '700b1c99f0b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gallery_item', schema=None) as batch_op:
        batch_op.alter_column('media_url',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
        batch_op.alter_column('media_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gallery_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('media_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('media_type', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.alter_column('image_url',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)

    # ### end Alembic commands ###
