"""Remove bind key from GalleryItem

Revision ID: d2013be24b70
Revises: 7d1bbd9e98af
Create Date: 2025-04-11 12:01:59.119814

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2013be24b70'
down_revision = '7d1bbd9e98af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gallery_item', schema=None) as batch_op:
        batch_op.alter_column('image_url',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
        batch_op.drop_column('media_type')
        batch_op.drop_column('media_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gallery_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('media_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('media_type', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.alter_column('image_url',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)

    # ### end Alembic commands ###
